"""empty message

Revision ID: 1a39cc96a44b
Revises: 61217175c420
Create Date: 2022-10-24 06:02:39.454968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a39cc96a44b'
down_revision = '61217175c420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cctv', sa.Column('Longitude', sa.Float(), nullable=False))
    op.drop_column('cctv', 'Longtitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cctv', sa.Column('Longtitude', mysql.FLOAT(), nullable=False))
    op.drop_column('cctv', 'Longitude')
    # ### end Alembic commands ###
