"""empty message

Revision ID: 36dffbd17142
Revises: 953ca689df27
Create Date: 2022-11-21 21:12:12.290307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dffbd17142'
down_revision = '953ca689df27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_history', sa.Column('CCTVName', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'flood_history', 'cctv', ['CCTVName'], ['Name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flood_history', type_='foreignkey')
    op.drop_column('flood_history', 'CCTVName')
    # ### end Alembic commands ###
