"""empty message

Revision ID: 41140c8630a3
Revises: 1f7108bd66ed
Create Date: 2022-10-25 08:30:16.787074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41140c8630a3'
down_revision = '1f7108bd66ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctv_status',
    sa.Column('CCTVID', sa.String(length=7), nullable=False),
    sa.Column('FloodingStage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CCTVID'], ['cctv.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CCTVID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cctv_status')
    # ### end Alembic commands ###
