"""empty message

Revision ID: 6a84745aa1ab
Revises: 41140c8630a3
Create Date: 2022-10-31 16:05:29.875819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a84745aa1ab'
down_revision = '41140c8630a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('Index', sa.Integer(), nullable=False),
    sa.Column('Address', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Type', sa.String(length=4), nullable=True),
    sa.Column('Area', sa.Integer(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter')
    # ### end Alembic commands ###
