"""empty message

Revision ID: 82b47e93efe4
Revises: b257fa8c5734
Create Date: 2022-11-13 17:08:36.916880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82b47e93efe4'
down_revision = 'b257fa8c5734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('memberID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cctvID', mysql.VARCHAR(length=7), nullable=False),
    sa.PrimaryKeyConstraint('memberID', 'cctvID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
