"""empty message

Revision ID: 909608591ff3
Revises: 7edd7d8222e4
Create Date: 2022-11-30 20:21:18.039204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909608591ff3'
down_revision = '7edd7d8222e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatlog',
    sa.Column('Index', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=20), nullable=True),
    sa.Column('Body', sa.Text(), nullable=True),
    sa.Column('Time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatlog')
    # ### end Alembic commands ###
