"""empty message

Revision ID: 953ca689df27
Revises: 3ecb7393567c
Create Date: 2022-11-17 20:43:25.417928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953ca689df27'
down_revision = '3ecb7393567c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cctv', sa.Column('Region', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cctv', 'Region')
    # ### end Alembic commands ###
