"""empty message

Revision ID: 9b6a5a73b355
Revises: 6a84745aa1ab
Create Date: 2022-11-04 22:59:52.442575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6a5a73b355'
down_revision = '6a84745aa1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posting',
    sa.Column('Index', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=False),
    sa.Column('Datetime', sa.DateTime(), nullable=False),
    sa.Column('ImageURL', sa.Text(), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['member.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting')
    # ### end Alembic commands ###
