"""empty message

Revision ID: b257fa8c5734
Revises: 9b6a5a73b355
Create Date: 2022-11-07 16:01:23.682208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b257fa8c5734'
down_revision = '9b6a5a73b355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting', 'ImageURL',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('posting', 'Content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting', 'Content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('posting', 'ImageURL',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
