"""empty message

Revision ID: bc758662f97c
Revises: a038409e435f
Create Date: 2022-12-06 12:32:57.260300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc758662f97c'
down_revision = 'a038409e435f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_history', sa.Column('StageChange', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_history', 'StageChange')
    # ### end Alembic commands ###
