"""empty message

Revision ID: c71fad895f82
Revises: 1a39cc96a44b
Create Date: 2022-10-24 06:04:45.598490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c71fad895f82'
down_revision = '1a39cc96a44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cctv', 'URL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cctv', sa.Column('URL', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
