"""empty message

Revision ID: cb878e91f721
Revises: c71fad895f82
Create Date: 2022-10-24 06:05:16.931530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb878e91f721'
down_revision = 'c71fad895f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cctv', sa.Column('URL', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cctv', 'URL')
    # ### end Alembic commands ###
