"""empty message

Revision ID: dda265b3c9e8
Revises: cb878e91f721
Create Date: 2022-10-24 19:42:19.055473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dda265b3c9e8'
down_revision = 'cb878e91f721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('ID', sa.String(length=20), nullable=False))
    op.add_column('member', sa.Column('Email', sa.String(length=120), nullable=False))
    op.add_column('member', sa.Column('Password', sa.String(length=100), nullable=False))
    op.drop_index('email', table_name='member')
    op.create_unique_constraint(None, 'member', ['Email'])
    op.drop_column('member', 'email')
    op.drop_column('member', 'id')
    op.drop_column('member', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('member', sa.Column('id', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('member', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'member', type_='unique')
    op.create_index('email', 'member', ['email'], unique=False)
    op.drop_column('member', 'Password')
    op.drop_column('member', 'Email')
    op.drop_column('member', 'ID')
    # ### end Alembic commands ###
