"""empty message

Revision ID: de784fee7bdd
Revises: 547e3384c535
Create Date: 2022-11-14 14:23:28.187244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de784fee7bdd'
down_revision = '547e3384c535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('memberID', sa.String(length=20), nullable=False),
    sa.Column('cctvID', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('memberID', 'cctvID', name='_bookmark_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    # ### end Alembic commands ###
